version: "2"
run:
  allow-parallel-runners: true
linters:
  default: none
  enable:
    - copyloopvar
    - dupl
    - errcheck
    - ginkgolinter
    - goconst
    - gocyclo
    - govet
    - ineffassign
    - lll
    - misspell
    - nakedret
    - prealloc
    - revive
    - staticcheck
    - unconvert
    - unparam
    - unused
  settings:
    revive:
      rules:
        - name: comment-spacings
        - name: import-shadowing
    goconst:
      min-len: 10
      min-occurrences: 10
    dupl:
      threshold: 3000
    gocyclo:
      min-complexity: 60
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - gen/.*$
    rules:
      - linters:
          - lll
        path: api/*
      - linters:
          - dupl
          - lll
        path: internal/*
      - linters:
          - errcheck
          - ineffassign
          - prealloc
          - unparam
          - goconst
          - gocyclo
          - staticcheck
          - lll
        path: ".*_test\\.go"
      - linters:
          - errcheck
          - goconst
          - prealloc
          - revive
          - unparam
        path: ".*test_helpers\\.go"
formatters:
  enable:
    - gofmt
    - goimports
  exclusions:
    generated: lax
    paths:
      - third_party$
      - builtin$
      - examples$
      - gen/.*$