apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "deptrack-operator.fullname" . }}-apikey-editor-role
  labels:
  {{- include "deptrack-operator.labels" . | nindent 4 }}
rules:
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - apikeys
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - apikeys/status
  verbs:
  - get
