---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: deptrack-operator-webhook-service
      namespace: deptrack-operator-system
      path: /validate-dependencytrack-mko-dev-v1alpha1-team
    caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUVkakNDQTE2Z0F3SUJBZ0lVUEJZU1R4Z2RSTTJsVDFiSW5Tc0F1aVNWME1Zd0RRWUpLb1pJaHZjTkFRRUwKQlFBd0pERWlNQ0FHQTFVRUF3d1paR1Z3ZEhKaFkyc3RiM0JsY21GMGIzSXRkMlZpYUc5dmF6QWVGdzB5TmpBNApNVEV4TnpBNU5UZGFGdzB6TmpBNE1EZ3hOekE1TlRoYU1DUXhJakFnQmdOVkJBTU1HV1JsY0hSeVlXTnJMVzl3ClpYSmhkRzl5TFhkbFltaHZiMnN3Z2dFaU1BMEdDU3FHU0liM0RRRUJBUVVBQTRJQkR3QXdnZ0VLQW9JQkFRQ2MKWlZNdElBYTlnOFFtZ3IwRlFKV2xOZHd0dHZjYjJQemEzMUtpZVZFQks2d1dYM1NHYUIyTHdMVk1IQnJzTXc4agpIbFBWZkdpcGxKNDAyMUQvZ1dFbkE0emtBTlAvdy9nWEZHSXhVdFRMNUJaaFJSZkEvSHpnWkdrNzlyQ1lTbHAzCnN0SjhKdzZoMituUzhYTDAzZTlBK1NjNTlqOGxRR2E1NE4zOWVHUEdoTlF5RUc5RStFdGJtMDB3aU9jcTlGVFoKZGpHeXNnQXllcGdlU0tpSnQ3VzNIUkY1UFZtYjFiN0JiTG8rNGZLcDhlYlF6aFFNOWNXbDRlMTkweS82K0JhRQpKbDdOT25lY2d1bW5CdGYrZTIzNUQyaFliWWJXb1lKUkZPV2JQUFBlZlI3NGFVOE1mbTdxNXJBK3k4STRHMVQ0Ci9ybWFVV2tQRlorYWh5WWlyRUw3QWdNQkFBR2pnZ0dlTUlJQm1qQWRCZ05WSFE0RUZnUVU5aDFZakxJUnFrVmUKdUJPcHNwSGxZUjJwVkh3d0h3WURWUjBqQkJnd0ZvQVU5aDFZakxJUnFrVmV1Qk9wc3BIbFlSMnBWSHd3RHdZRApWUjBUQVFIL0JBVXdBd0VCL3pDQ0FVVUdBMVVkRVFTQ0FUd3dnZ0U0Z2tGa1pYQjBjbUZqYXkxdmNHVnlZWFJ2CmNpMWpiMjUwY205c2JHVnlMVzFoYm1GblpYSXVaR1Z3ZEhKaFkyc3RiM0JsY21GMGIzSXRjM2x6ZEdWdExuTjIKWTRKUFpHVndkSEpoWTJzdGIzQmxjbUYwYjNJdFkyOXVkSEp2Ykd4bGNpMXRZVzVoWjJWeUxtUmxjSFJ5WVdOcgpMVzl3WlhKaGRHOXlMWE41YzNSbGJTNXpkbU11WTJ4MWMzUmxjaTVzYjJOaGJJSkpaR1Z3ZEhKaFkyc3RiM0JsCmNtRjBiM0l0WTI5dWRISnZiR3hsY2kxdFlXNWhaMlZ5TFhkbFltaHZiMnN1WkdWd2RISmhZMnN0YjNCbGNtRjAKYjNJdGMzbHpkR1Z0TG5OMlk0SlhaR1Z3ZEhKaFkyc3RiM0JsY21GMGIzSXRZMjl1ZEhKdmJHeGxjaTF0WVc1aApaMlZ5TFhkbFltaHZiMnN1WkdWd2RISmhZMnN0YjNCbGNtRjBiM0l0YzNsemRHVnRMbk4yWXk1amJIVnpkR1Z5CkxteHZZMkZzTUEwR0NTcUdTSWIzRFFFQkN3VUFBNElCQVFCQVEzd3VRRlllT2RoZ2RGYVB4Y2xycm50SU0ySFgKYU9mcExJQ0czOUxDb012VGhBWWxQVzJXVEpzQ0NBY3NBcnA1dk1BZnpESmVNRFVKYmliSGdFV0p0bldhM081dQpEQVVPU1JzQ1U4UDBBWHNCRzRaTVZuTzI2M2RnV3VsMjdReitpUGwvNkpKVklCR21FT2lpK24wOEs5OUN1NEw2CjY1dUJjNysvMXNPSVpwU0d0WE1JM2hXZW53NUJzSzZ2L0NVYmN6aXp0STF2S3NJZXNyNUR1d1lnOGNLOFhKTWsKcTdJL2R4R05KWUVaenJmL0pDWlh5aGlYSkZCZ3BnaWlBbE5laU1BQytpVUxOYlhSUSt1c2J1TkNMWC96bDgydgppd3loeVpmd3lVREd1dW1JZlJZZGJ3UUNSa3NNamsyVUhtZTJ6OWJJUkl0UXJEVFEwOVRRZGVDYgotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg==
  failurePolicy: Fail
  name: team.validating.dependencytrack.mko.dev
  rules:
  - apiGroups:
    - dependencytrack.mko.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - teams
  sideEffects: None
