apiVersion: v1
kind: Service
metadata:
  name: webhook-service
  labels:
    control-plane: controller-manager
spec:
  type: ClusterIP
  selector:
    control-plane: controller-manager
  ports:
    - port: 443
      protocol: TCP
      targetPort: 9443
      name: https-webhook