# This rule is not used by the project deptrack-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants write access to notificationrules within a namespace.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deptrack-operator
    app.kubernetes.io/managed-by: kustomize
  name: notificationrule-editor-role
rules:
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - notificationrules
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - notificationrules/status
  verbs:
  - get
  - patch
  - update