---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - apikeys
  - teams
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - apikeys/finalizers
  - teams/finalizers
  verbs:
  - update
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - apikeys/status
  - teams/status
  verbs:
  - get
  - patch
  - update
