# This rule is not used by the project deptrack-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Provides read-only access to teams within a namespace.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: deptrack-operator
    app.kubernetes.io/managed-by: kustomize
  name: team-viewer-role
rules:
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - teams
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - dependencytrack.mko.dev
  resources:
  - teams/status
  verbs:
  - get