apiVersion: operators.coreos.com/v1alpha1
kind: ClusterServiceVersion
metadata:
  annotations:
    alm-examples: '[]'
    capabilities: Basic Install
  name: deptrack-operator.v0.0.0
  namespace: placeholder
spec:
  apiservicedefinitions: {}
  customresourcedefinitions:
    owned:
    - description: Team is the Schema for the teams API.
      displayName: Team
      kind: Team
      name: teams.dependencytrack.mko.dev
      version: v1alpha1
  description: Allows configuration of dependencytrack
  displayName: DependencyTrack Operator
  icon:
  - base64data: ""
    mediatype: ""
  install:
    spec:
      deployments: null
    strategy: ""
  installModes:
  - supported: false
    type: OwnNamespace
  - supported: false
    type: SingleNamespace
  - supported: false
    type: MultiNamespace
  - supported: true
    type: AllNamespaces
  keywords:
  - dependencytrack
  - owasp
  - security
  links:
  - name: Deptrack Operator
    url: https://deptrack-operator.domain
  maintainers:
  - email: martin@mko.dev
    name: Martin Koppehel
  maturity: alpha
  provider:
    name: deptrack-operator
  version: 0.0.0
