apiVersion: dependencytrack.mko.dev/v1alpha1
kind: APIKey
metadata:
  labels:
    app.kubernetes.io/name: deptrack-operator
    app.kubernetes.io/managed-by: kustomize
  name: apikey-sample
spec:
  teamRef: team-sample
  secretName: apikey-sample-secret
  comment: "Sample API key"