## Append samples of your project ##
resources:
- dependencytrack_v1alpha1_team.yaml
- dependencytrack_v1alpha1_apikey.yaml
- dependencytrack_v1alpha1_policy.yaml
# +kubebuilder:scaffold:manifestskustomizesamples
