apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: {{ include "dependencytrack-operator.fullname" . }}-webhook-server-cert
  labels:
  {{- include "dependencytrack-operator.labels" . | nindent 4 }}
spec:
  dnsNames:
  - '{{ include "dependencytrack-operator.fullname" . }}-webhook-service'
  - '{{ include "dependencytrack-operator.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc'
  - '{{ include "dependencytrack-operator.fullname" . }}-webhook-service.{{ .Release.Namespace
    }}.svc.{{ .Values.kubernetesClusterDomain }}'
  issuerRef:
    kind: Issuer
    name: '{{ include "dependencytrack-operator.fullname" . }}-self-signed-issuer'
  privateKey:
    algorithm: RSA
    size: 2048
  secretName: {{ include "dependencytrack-operator.fullname" . }}-webhook-server-cert
