apiVersion: cert-manager.io/v1
kind: Issuer
metadata:
  name: {{ include "dependencytrack-operator.fullname" . }}-self-signed-issuer
  labels:
  {{- include "dependencytrack-operator.labels" . | nindent 4 }}
spec:
  selfSigned: {}
