apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: deptrack-operator-validator
  annotations:
    cert-manager.io/inject-ca-from: {{ .Release.Namespace }}/deptrack-operator-webhook-server-cert
  labels:
  {{- include "dependencytrack-operator.labels" . | nindent 4 }}
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: deptrack-operator-webhook-service
      namespace: {{ .Release.Namespace }}
      path: /validate-dependencytrack-mko-dev-v1alpha1-team
  failurePolicy: Fail
  name: team.validating.dependencytrack.mko.dev
  rules:
  - apiGroups:
    - dependencytrack.mko.dev
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - teams
  sideEffects: None
