apiVersion: v1
kind: Service
metadata:
  name: deptrack-operator-webhook-service
  labels:
    control-plane: controller-manager
  {{- include "dependencytrack-operator.labels" . | nindent 4 }}
spec:
  type: {{ .Values.webhookService.type }}
  selector:
    control-plane: controller-manager
    {{- include "dependencytrack-operator.selectorLabels" . | nindent 4 }}
  ports:
  {{- .Values.webhookService.ports | toYaml | nindent 2 }}
